apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pybsposter.fullname" . }}
  labels:
    {{- include "pybsposter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "pybsposter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pybsposter.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

