apiVersion: v1
kind: Service
metadata:
  name: {{ include "pybsposter.fullname" . }}
  labels:
    {{- include "pybsposter.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "pybsposter.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

